ALTER TABLE public.agent_call_sessions ADD CONSTRAINT agent_call_sessions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE public.automation_approvals ADD CONSTRAINT automation_approvals_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.automation_approvals ADD CONSTRAINT automation_approvals_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.contact_tag_assignments ADD CONSTRAINT contact_tag_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.email_bulk_campaigns ADD CONSTRAINT email_bulk_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE public.email_conversations ADD CONSTRAINT email_conversations_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.email_suppression_list ADD CONSTRAINT email_suppression_list_suppressed_by_fkey FOREIGN KEY (suppressed_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.email_templates ADD CONSTRAINT email_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE public.inventory_items ADD CONSTRAINT inventory_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.loan_applications ADD CONSTRAINT loan_applications_referred_by_fkey FOREIGN KEY (referred_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.loan_disbursements ADD CONSTRAINT loan_disbursements_proof_uploaded_by_fkey FOREIGN KEY (proof_uploaded_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.loan_generated_documents ADD CONSTRAINT loan_generated_documents_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.loan_payments ADD CONSTRAINT loan_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.nupay_upi_transactions ADD CONSTRAINT nupay_upi_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.organization_subscriptions ADD CONSTRAINT organization_subscriptions_override_by_fkey FOREIGN KEY (override_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.otp_verifications ADD CONSTRAINT otp_verifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.outbound_webhooks ADD CONSTRAINT outbound_webhooks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_initiated_by_fkey FOREIGN KEY (initiated_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.pipeline_movement_history ADD CONSTRAINT pipeline_movement_history_moved_by_fkey FOREIGN KEY (moved_by) REFERENCES auth.users(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE public.redefine_data_repository ADD CONSTRAINT redefine_data_repository_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.redefine_repository_audit ADD CONSTRAINT redefine_repository_audit_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.saved_reports ADD CONSTRAINT saved_reports_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE public.service_usage_logs ADD CONSTRAINT service_usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.subscription_audit_log ADD CONSTRAINT subscription_audit_log_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.subscription_invoices ADD CONSTRAINT subscription_invoices_waived_by_fkey FOREIGN KEY (waived_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.subscription_pricing ADD CONSTRAINT subscription_pricing_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.team_members ADD CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE public.teams ADD CONSTRAINT teams_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES auth.users(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE public.user_referral_codes ADD CONSTRAINT user_referral_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE public.videokyc_recordings ADD CONSTRAINT videokyc_recordings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.wallet_transactions ADD CONSTRAINT wallet_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.whatsapp_bulk_campaigns ADD CONSTRAINT whatsapp_bulk_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) NOT VALID;
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id) NOT VALID;
