ALTER TABLE public.activity_participants ADD CONSTRAINT activity_participants_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES contact_activities(id) ON DELETE CASCADE;
ALTER TABLE public.activity_participants ADD CONSTRAINT activity_participants_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public.activity_participants ADD CONSTRAINT activity_participants_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.activity_participants ADD CONSTRAINT activity_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.agent_call_sessions ADD CONSTRAINT agent_call_sessions_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id);
ALTER TABLE public.agent_call_sessions ADD CONSTRAINT agent_call_sessions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.approval_rules ADD CONSTRAINT approval_rules_approval_type_id_fkey FOREIGN KEY (approval_type_id) REFERENCES approval_types(id) ON DELETE CASCADE;
ALTER TABLE public.approval_rules ADD CONSTRAINT approval_rules_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.approval_types ADD CONSTRAINT approval_types_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.automation_ab_tests ADD CONSTRAINT automation_ab_tests_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.automation_ab_tests ADD CONSTRAINT automation_ab_tests_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES email_automation_rules(id) ON DELETE CASCADE;
ALTER TABLE public.automation_approvals ADD CONSTRAINT automation_approvals_execution_id_fkey FOREIGN KEY (execution_id) REFERENCES email_automation_executions(id) ON DELETE CASCADE;
ALTER TABLE public.automation_approvals ADD CONSTRAINT automation_approvals_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.automation_approvals ADD CONSTRAINT automation_approvals_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES email_automation_rules(id) ON DELETE CASCADE;
ALTER TABLE public.automation_performance_daily ADD CONSTRAINT automation_performance_daily_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.automation_performance_daily ADD CONSTRAINT automation_performance_daily_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES email_automation_rules(id) ON DELETE CASCADE;
ALTER TABLE public.blog_posts ADD CONSTRAINT blog_posts_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.call_dispositions ADD CONSTRAINT call_dispositions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.call_logs ADD CONSTRAINT call_logs_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES contact_activities(id);
ALTER TABLE public.call_logs ADD CONSTRAINT call_logs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.call_logs ADD CONSTRAINT call_logs_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES loan_applicants(id) ON DELETE SET NULL;
ALTER TABLE public.call_logs ADD CONSTRAINT call_logs_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public.call_logs ADD CONSTRAINT call_logs_disposition_id_fkey FOREIGN KEY (disposition_id) REFERENCES call_dispositions(id);
ALTER TABLE public.call_logs ADD CONSTRAINT call_logs_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE SET NULL;
ALTER TABLE public.call_logs ADD CONSTRAINT call_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.call_logs ADD CONSTRAINT call_logs_sub_disposition_id_fkey FOREIGN KEY (sub_disposition_id) REFERENCES call_sub_dispositions(id);
ALTER TABLE public.call_sub_dispositions ADD CONSTRAINT call_sub_dispositions_disposition_id_fkey FOREIGN KEY (disposition_id) REFERENCES call_dispositions(id) ON DELETE CASCADE;
ALTER TABLE public.call_sub_dispositions ADD CONSTRAINT call_sub_dispositions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_analytics ADD CONSTRAINT campaign_analytics_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.campaign_insights ADD CONSTRAINT campaign_insights_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.communication_templates ADD CONSTRAINT communication_templates_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.connector_logs ADD CONSTRAINT connector_logs_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public.connector_logs ADD CONSTRAINT connector_logs_form_id_fkey FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE;
ALTER TABLE public.connector_logs ADD CONSTRAINT connector_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.contact_activities ADD CONSTRAINT contact_activities_call_disposition_id_fkey FOREIGN KEY (call_disposition_id) REFERENCES call_dispositions(id) ON DELETE SET NULL;
ALTER TABLE public.contact_activities ADD CONSTRAINT contact_activities_call_sub_disposition_id_fkey FOREIGN KEY (call_sub_disposition_id) REFERENCES call_sub_dispositions(id) ON DELETE SET NULL;
ALTER TABLE public.contact_activities ADD CONSTRAINT contact_activities_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.contact_activities ADD CONSTRAINT contact_activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.contact_activities ADD CONSTRAINT contact_activities_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.contact_custom_fields ADD CONSTRAINT contact_custom_fields_custom_field_id_fkey FOREIGN KEY (custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE;
ALTER TABLE public.contact_emails ADD CONSTRAINT contact_emails_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.contact_enrichment_runs ADD CONSTRAINT contact_enrichment_runs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.contact_lead_scores ADD CONSTRAINT contact_lead_scores_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.contact_lead_scores ADD CONSTRAINT contact_lead_scores_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.contact_phones ADD CONSTRAINT contact_phones_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.contact_tag_assignments ADD CONSTRAINT contact_tag_assignments_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.contact_tag_assignments ADD CONSTRAINT contact_tag_assignments_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.contact_tag_assignments ADD CONSTRAINT contact_tag_assignments_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES contact_tags(id) ON DELETE CASCADE;
ALTER TABLE public.contact_tags ADD CONSTRAINT contact_tags_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_assigned_team_id_fkey FOREIGN KEY (assigned_team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_pipeline_stage_id_fkey FOREIGN KEY (pipeline_stage_id) REFERENCES pipeline_stages(id) ON DELETE SET NULL;
ALTER TABLE public.designation_feature_access ADD CONSTRAINT designation_feature_access_designation_id_fkey FOREIGN KEY (designation_id) REFERENCES designations(id) ON DELETE CASCADE;
ALTER TABLE public.designation_feature_access ADD CONSTRAINT designation_feature_access_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.document_esign_requests ADD CONSTRAINT document_esign_requests_application_id_fkey FOREIGN KEY (application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.document_esign_requests ADD CONSTRAINT document_esign_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.document_esign_requests ADD CONSTRAINT document_esign_requests_document_id_fkey FOREIGN KEY (document_id) REFERENCES loan_generated_documents(id) ON DELETE SET NULL;
ALTER TABLE public.document_esign_requests ADD CONSTRAINT document_esign_requests_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id);
ALTER TABLE public.email_automation_cooldowns ADD CONSTRAINT email_automation_cooldowns_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_cooldowns ADD CONSTRAINT email_automation_cooldowns_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_cooldowns ADD CONSTRAINT email_automation_cooldowns_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES email_automation_rules(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_daily_limits ADD CONSTRAINT email_automation_daily_limits_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_daily_limits ADD CONSTRAINT email_automation_daily_limits_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_executions ADD CONSTRAINT email_automation_executions_ab_test_id_fkey FOREIGN KEY (ab_test_id) REFERENCES automation_ab_tests(id) ON DELETE SET NULL;
ALTER TABLE public.email_automation_executions ADD CONSTRAINT email_automation_executions_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_executions ADD CONSTRAINT email_automation_executions_email_conversation_id_fkey FOREIGN KEY (email_conversation_id) REFERENCES email_conversations(id) ON DELETE SET NULL;
ALTER TABLE public.email_automation_executions ADD CONSTRAINT email_automation_executions_email_template_id_fkey FOREIGN KEY (email_template_id) REFERENCES email_templates(id) ON DELETE SET NULL;
ALTER TABLE public.email_automation_executions ADD CONSTRAINT email_automation_executions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_executions ADD CONSTRAINT email_automation_executions_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES email_automation_rules(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_rule_dependencies ADD CONSTRAINT email_automation_rule_dependencies_depends_on_rule_id_fkey FOREIGN KEY (depends_on_rule_id) REFERENCES email_automation_rules(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_rule_dependencies ADD CONSTRAINT email_automation_rule_dependencies_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_rule_dependencies ADD CONSTRAINT email_automation_rule_dependencies_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES email_automation_rules(id) ON DELETE CASCADE;
ALTER TABLE public.email_automation_rules ADD CONSTRAINT email_automation_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.email_automation_rules ADD CONSTRAINT email_automation_rules_email_template_id_fkey FOREIGN KEY (email_template_id) REFERENCES email_templates(id) ON DELETE SET NULL;
ALTER TABLE public.email_automation_rules ADD CONSTRAINT email_automation_rules_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_bulk_campaigns ADD CONSTRAINT email_bulk_campaigns_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_bulk_campaigns ADD CONSTRAINT email_bulk_campaigns_template_id_fkey FOREIGN KEY (template_id) REFERENCES email_templates(id) ON DELETE SET NULL;
ALTER TABLE public.email_campaign_recipients ADD CONSTRAINT email_campaign_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES email_bulk_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.email_campaign_recipients ADD CONSTRAINT email_campaign_recipients_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public.email_conversations ADD CONSTRAINT email_conversations_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id);
ALTER TABLE public.email_conversations ADD CONSTRAINT email_conversations_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id);
ALTER TABLE public.email_conversations ADD CONSTRAINT email_conversations_replied_to_message_id_fkey FOREIGN KEY (replied_to_message_id) REFERENCES email_conversations(id);
ALTER TABLE public.email_engagement_patterns ADD CONSTRAINT email_engagement_patterns_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.email_engagement_patterns ADD CONSTRAINT email_engagement_patterns_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_settings ADD CONSTRAINT email_settings_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_suppression_list ADD CONSTRAINT email_suppression_list_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_templates ADD CONSTRAINT email_templates_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.email_unsubscribes ADD CONSTRAINT email_unsubscribes_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public.email_unsubscribes ADD CONSTRAINT email_unsubscribes_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.error_logs ADD CONSTRAINT error_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.error_logs ADD CONSTRAINT error_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.exotel_settings ADD CONSTRAINT exotel_settings_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.form_fields ADD CONSTRAINT form_fields_custom_field_id_fkey FOREIGN KEY (custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE;
ALTER TABLE public.form_fields ADD CONSTRAINT form_fields_form_id_fkey FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE;
ALTER TABLE public.google_oauth_tokens ADD CONSTRAINT google_oauth_tokens_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.import_jobs ADD CONSTRAINT import_jobs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id);
ALTER TABLE public.inventory_items ADD CONSTRAINT inventory_items_import_job_id_fkey FOREIGN KEY (import_job_id) REFERENCES import_jobs(id);
ALTER TABLE public.loan_applicants ADD CONSTRAINT loan_applicants_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_application_forms ADD CONSTRAINT loan_application_forms_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_applications ADD CONSTRAINT loan_applications_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES profiles(id);
ALTER TABLE public.loan_applications ADD CONSTRAINT loan_applications_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.loan_applications ADD CONSTRAINT loan_applications_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public.loan_applications ADD CONSTRAINT loan_applications_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.loan_applications ADD CONSTRAINT loan_applications_form_id_fkey FOREIGN KEY (form_id) REFERENCES loan_application_forms(id);
ALTER TABLE public.loan_applications ADD CONSTRAINT loan_applications_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_applications ADD CONSTRAINT loan_applications_parent_application_id_fkey FOREIGN KEY (parent_application_id) REFERENCES loan_applications(id);
ALTER TABLE public.loan_approvals ADD CONSTRAINT loan_approvals_approver_id_fkey FOREIGN KEY (approver_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.loan_approvals ADD CONSTRAINT loan_approvals_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_assignment_config ADD CONSTRAINT loan_assignment_config_last_assigned_user_id_fkey FOREIGN KEY (last_assigned_user_id) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.loan_assignment_config ADD CONSTRAINT loan_assignment_config_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_audit_log ADD CONSTRAINT loan_audit_log_action_by_fkey FOREIGN KEY (action_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.loan_audit_log ADD CONSTRAINT loan_audit_log_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_bank_analysis ADD CONSTRAINT loan_bank_analysis_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES loan_applicants(id) ON DELETE CASCADE;
ALTER TABLE public.loan_credit_bureau_reports ADD CONSTRAINT loan_credit_bureau_reports_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES loan_applicants(id) ON DELETE CASCADE;
ALTER TABLE public.loan_deviations ADD CONSTRAINT loan_deviations_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.loan_deviations ADD CONSTRAINT loan_deviations_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_deviations ADD CONSTRAINT loan_deviations_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.loan_disbursements ADD CONSTRAINT loan_disbursements_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_disbursements ADD CONSTRAINT loan_disbursements_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id);
ALTER TABLE public.loan_disbursements ADD CONSTRAINT loan_disbursements_sanction_id_fkey FOREIGN KEY (sanction_id) REFERENCES loan_sanctions(id) ON DELETE SET NULL;
ALTER TABLE public.loan_document_types ADD CONSTRAINT loan_document_types_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_documents ADD CONSTRAINT loan_documents_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES loan_applicants(id) ON DELETE CASCADE;
ALTER TABLE public.loan_documents ADD CONSTRAINT loan_documents_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_documents ADD CONSTRAINT loan_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.loan_eligibility ADD CONSTRAINT loan_eligibility_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_employment_details ADD CONSTRAINT loan_employment_details_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES loan_applicants(id) ON DELETE CASCADE;
ALTER TABLE public.loan_generated_documents ADD CONSTRAINT loan_generated_documents_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_generated_documents ADD CONSTRAINT loan_generated_documents_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id);
ALTER TABLE public.loan_generated_documents ADD CONSTRAINT loan_generated_documents_sanction_id_fkey FOREIGN KEY (sanction_id) REFERENCES loan_sanctions(id);
ALTER TABLE public.loan_income_summaries ADD CONSTRAINT loan_income_summaries_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES loan_applicants(id) ON DELETE SET NULL;
ALTER TABLE public.loan_income_summaries ADD CONSTRAINT loan_income_summaries_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_income_summaries ADD CONSTRAINT loan_income_summaries_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_negative_areas ADD CONSTRAINT loan_negative_areas_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_payments ADD CONSTRAINT loan_payments_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_payments ADD CONSTRAINT loan_payments_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_payments ADD CONSTRAINT loan_payments_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES loan_repayment_schedule(id) ON DELETE SET NULL;
ALTER TABLE public.loan_policy_rules ADD CONSTRAINT loan_policy_rules_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_policy_rules ADD CONSTRAINT loan_policy_rules_product_id_fkey FOREIGN KEY (product_id) REFERENCES loan_products(id) ON DELETE CASCADE;
ALTER TABLE public.loan_products ADD CONSTRAINT loan_products_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_referrals ADD CONSTRAINT loan_referrals_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES loan_applicants(id) ON DELETE CASCADE;
ALTER TABLE public.loan_referrals ADD CONSTRAINT loan_referrals_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_referrals ADD CONSTRAINT loan_referrals_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_repayment_schedule ADD CONSTRAINT loan_repayment_schedule_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_repayment_schedule ADD CONSTRAINT loan_repayment_schedule_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.loan_repayment_schedule ADD CONSTRAINT loan_repayment_schedule_sanction_id_fkey FOREIGN KEY (sanction_id) REFERENCES loan_sanctions(id) ON DELETE CASCADE;
ALTER TABLE public.loan_sanctions ADD CONSTRAINT loan_sanctions_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_stage_history ADD CONSTRAINT loan_stage_history_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_stage_history ADD CONSTRAINT loan_stage_history_moved_by_fkey FOREIGN KEY (moved_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.loan_verifications ADD CONSTRAINT loan_verifications_applicant_id_fkey FOREIGN KEY (applicant_id) REFERENCES loan_applicants(id) ON DELETE CASCADE;
ALTER TABLE public.loan_verifications ADD CONSTRAINT loan_verifications_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.loan_verifications ADD CONSTRAINT loan_verifications_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.nupay_auth_tokens ADD CONSTRAINT nupay_auth_tokens_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.nupay_banks ADD CONSTRAINT nupay_banks_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.nupay_config ADD CONSTRAINT nupay_config_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.nupay_mandates ADD CONSTRAINT nupay_mandates_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public.nupay_mandates ADD CONSTRAINT nupay_mandates_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id);
ALTER TABLE public.nupay_mandates ADD CONSTRAINT nupay_mandates_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.nupay_mandates ADD CONSTRAINT nupay_mandates_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.nupay_upi_auth_tokens ADD CONSTRAINT nupay_upi_auth_tokens_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.nupay_upi_transactions ADD CONSTRAINT nupay_upi_transactions_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE CASCADE;
ALTER TABLE public.nupay_upi_transactions ADD CONSTRAINT nupay_upi_transactions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.nupay_upi_transactions ADD CONSTRAINT nupay_upi_transactions_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES loan_repayment_schedule(id) ON DELETE SET NULL;
ALTER TABLE public.operation_queue ADD CONSTRAINT operation_queue_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.operation_queue ADD CONSTRAINT operation_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.org_business_hours ADD CONSTRAINT org_business_hours_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.organization_loan_settings ADD CONSTRAINT organization_loan_settings_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id);
ALTER TABLE public.organization_subscriptions ADD CONSTRAINT organization_subscriptions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.otp_verifications ADD CONSTRAINT otp_verifications_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.otp_verifications ADD CONSTRAINT otp_verifications_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.outbound_webhook_logs ADD CONSTRAINT outbound_webhook_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.outbound_webhook_logs ADD CONSTRAINT outbound_webhook_logs_webhook_id_fkey FOREIGN KEY (webhook_id) REFERENCES outbound_webhooks(id) ON DELETE CASCADE;
ALTER TABLE public.outbound_webhooks ADD CONSTRAINT outbound_webhooks_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES subscription_invoices(id);
ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pipeline_benchmarks ADD CONSTRAINT pipeline_benchmarks_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pipeline_benchmarks ADD CONSTRAINT pipeline_benchmarks_stage_id_fkey FOREIGN KEY (stage_id) REFERENCES pipeline_stages(id) ON DELETE CASCADE;
ALTER TABLE public.pipeline_movement_history ADD CONSTRAINT pipeline_movement_history_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.pipeline_movement_history ADD CONSTRAINT pipeline_movement_history_from_stage_id_fkey FOREIGN KEY (from_stage_id) REFERENCES pipeline_stages(id) ON DELETE SET NULL;
ALTER TABLE public.pipeline_movement_history ADD CONSTRAINT pipeline_movement_history_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.pipeline_movement_history ADD CONSTRAINT pipeline_movement_history_to_stage_id_fkey FOREIGN KEY (to_stage_id) REFERENCES pipeline_stages(id) ON DELETE SET NULL;
ALTER TABLE public.pipeline_stages ADD CONSTRAINT pipeline_stages_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_designation_id_fkey FOREIGN KEY (designation_id) REFERENCES designations(id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.redefine_data_repository ADD CONSTRAINT redefine_data_repository_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.redefine_repository_audit ADD CONSTRAINT redefine_repository_audit_repository_record_id_fkey FOREIGN KEY (repository_record_id) REFERENCES redefine_data_repository(id) ON DELETE CASCADE;
ALTER TABLE public.reporting_hierarchy ADD CONSTRAINT reporting_hierarchy_designation_id_fkey FOREIGN KEY (designation_id) REFERENCES designations(id) ON DELETE CASCADE;
ALTER TABLE public.reporting_hierarchy ADD CONSTRAINT reporting_hierarchy_reports_to_designation_id_fkey FOREIGN KEY (reports_to_designation_id) REFERENCES designations(id) ON DELETE CASCADE;
ALTER TABLE public.saved_reports ADD CONSTRAINT saved_reports_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.service_usage_logs ADD CONSTRAINT service_usage_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.service_usage_logs ADD CONSTRAINT service_usage_logs_wallet_transaction_id_fkey FOREIGN KEY (wallet_transaction_id) REFERENCES wallet_transactions(id);
ALTER TABLE public.sms_automation_cooldowns ADD CONSTRAINT sms_automation_cooldowns_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.sms_automation_cooldowns ADD CONSTRAINT sms_automation_cooldowns_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.sms_automation_cooldowns ADD CONSTRAINT sms_automation_cooldowns_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES sms_automation_rules(id) ON DELETE CASCADE;
ALTER TABLE public.sms_automation_executions ADD CONSTRAINT sms_automation_executions_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public.sms_automation_executions ADD CONSTRAINT sms_automation_executions_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE SET NULL;
ALTER TABLE public.sms_automation_executions ADD CONSTRAINT sms_automation_executions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.sms_automation_executions ADD CONSTRAINT sms_automation_executions_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES sms_automation_rules(id) ON DELETE CASCADE;
ALTER TABLE public.sms_automation_executions ADD CONSTRAINT sms_automation_executions_sms_message_id_fkey FOREIGN KEY (sms_message_id) REFERENCES sms_messages(id) ON DELETE SET NULL;
ALTER TABLE public.sms_automation_rules ADD CONSTRAINT sms_automation_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.sms_automation_rules ADD CONSTRAINT sms_automation_rules_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.sms_automation_rules ADD CONSTRAINT sms_automation_rules_sms_template_id_fkey FOREIGN KEY (sms_template_id) REFERENCES communication_templates(id) ON DELETE SET NULL;
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_loan_application_id_fkey FOREIGN KEY (loan_application_id) REFERENCES loan_applications(id) ON DELETE SET NULL;
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES profiles(id) ON DELETE SET NULL;
ALTER TABLE public.sms_messages ADD CONSTRAINT sms_messages_template_id_fkey FOREIGN KEY (template_id) REFERENCES communication_templates(id) ON DELETE SET NULL;
ALTER TABLE public.sms_templates ADD CONSTRAINT sms_templates_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.subscription_audit_log ADD CONSTRAINT subscription_audit_log_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id);
ALTER TABLE public.subscription_invoices ADD CONSTRAINT subscription_invoices_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.subscription_notifications ADD CONSTRAINT subscription_notifications_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES subscription_invoices(id);
ALTER TABLE public.subscription_notifications ADD CONSTRAINT subscription_notifications_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.tasks ADD CONSTRAINT tasks_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.team_members ADD CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.teams ADD CONSTRAINT teams_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.user_referral_codes ADD CONSTRAINT user_referral_codes_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE public.videokyc_recordings ADD CONSTRAINT videokyc_recordings_application_id_fkey FOREIGN KEY (application_id) REFERENCES loan_applications(id);
ALTER TABLE public.videokyc_recordings ADD CONSTRAINT videokyc_recordings_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id);
ALTER TABLE public.wallet_transactions ADD CONSTRAINT wallet_transactions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.wallet_transactions ADD CONSTRAINT wallet_transactions_payment_transaction_id_fkey FOREIGN KEY (payment_transaction_id) REFERENCES payment_transactions(id);
ALTER TABLE public.whatsapp_bulk_campaigns ADD CONSTRAINT whatsapp_bulk_campaigns_template_id_fkey FOREIGN KEY (template_id) REFERENCES communication_templates(id);
ALTER TABLE public.whatsapp_campaign_recipients ADD CONSTRAINT whatsapp_campaign_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES whatsapp_bulk_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.whatsapp_campaign_recipients ADD CONSTRAINT whatsapp_campaign_recipients_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id);
ALTER TABLE public.whatsapp_campaign_recipients ADD CONSTRAINT whatsapp_campaign_recipients_message_id_fkey FOREIGN KEY (message_id) REFERENCES whatsapp_messages(id);
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE;
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_replied_to_message_id_fkey FOREIGN KEY (replied_to_message_id) REFERENCES whatsapp_messages(id);
ALTER TABLE public.whatsapp_messages ADD CONSTRAINT whatsapp_messages_template_id_fkey FOREIGN KEY (template_id) REFERENCES communication_templates(id);
ALTER TABLE public.whatsapp_settings ADD CONSTRAINT whatsapp_settings_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
